services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: >
      sh -c "cd app && python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 core.asgi:application"