# Generated by Django 6.0.4 on 2026-05-05 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('breed', models.CharField(choices=[('persian', 'Персидский'), ('sphynx', 'Сфинкс'), ('bengal', 'Бенгальский'), ('maine_coon', 'Мейн-кун'), ('british', 'Британский'), ('siamese', 'Сиамский')], max_length=50, verbose_name='Порода')),
                ('is_fluffy', models.BooleanField(default=True, verbose_name='Пушистый')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
